ticketing/src/main/java/org/D7noun/dto/TB.java
package org.D7noun.dto;

import java.io.Serializable;
import java.text.DecimalFormat;
import java.util.Comparator;

public class TB implements Serializable, Comparator<TB> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String code;
	private String name;

	private double debit;
	private double credit;

	public TB() {
		super();
	}

	public TB(String code, String name, double debit, double credit) {
		super();
		this.code = code;
		this.name = name;
		this.debit = debit;
		this.credit = credit;
	}

	/**
	 * @return the code
	 */
	public String getCode() {
		return code;
	}

	/**
	 * @param code the code to set
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the debit
	 */
	public double getDebit() {
		if (debit < 0) {
			debit = debit * -1;
		}
		return debit;
	}

	public String getDebitStr() {
		if (debit < 0) {
			debit = debit * -1;
		}
		DecimalFormat decimalFormat = new DecimalFormat("#,###.00");
		String result = decimalFormat.format(debit);
		if (result.equals(".00")) {
			return "0.00";
		}
		return result;
	}

//	public String getDebitStr() {
//		return String.format("%.02f", getDebit());
//	}

	/**
	 * @param debit the debit to set
	 */
	public void setDebit(double debit) {
		this.debit = debit;
	}

	/**
	 * @return the credit
	 */
	public double getCredit() {
		if (credit < 0) {
			credit = credit * -1;
		}
		return credit;
	}

	public String getCreditStr() {
		if (credit < 0) {
			credit = credit * -1;
		}
		DecimalFormat decimalFormat = new DecimalFormat("#,###.00");
		String result = decimalFormat.format(credit);
		if (result.equals(".00")) {
			return "0.00";
		}
		return result;
	}

//	public String getCreditStr() {
//		return String.format("%.02f", getCredit());
//	}

	/**
	 * @param credit the credit to set
	 */
	public void setCredit(double credit) {
		this.credit = credit;
	}

	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public double getBalance() {
		return debit - credit;
	}

	public String getBalanceStr() {
		DecimalFormat decimalFormat = new DecimalFormat("#,###.00");
		double balance = getBalance();
		String result = decimalFormat.format(balance);
		if (balance <= 0) {
			result = decimalFormat.format(balance * -1);
		}
		if (result.equals(".00")) {
			return "0.00";
		}
		return result;
	}

//	public String getBalanceStr() {
//		if (getBalance() > 0) {
//			return String.format("%.02f", getBalance());
//		} else {
//			return String.format("%.02f", -1 * getBalance());
//		}
//	}

	public String getCrDr() {
		if (getBalance() >= 0) {
			return "DR";
		}
		return "CR";
	}

	@Override
	public int compare(TB o1, TB o2) {
		return o1.getCode().compareTo(o2.getCode());
	}

}

ticketing/src/main/java/org/D7noun/controllers/AccountReportController.java
package org.D7noun.controllers;

import java.io.ByteArrayOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.D7noun.abstraction.GeneralUtility;
import org.D7noun.dto.AccountReportDto;
import org.D7noun.dto.AccountReportDto.CRDR;
import org.D7noun.facades.AccountFacade;
import org.D7noun.facades.ItemFacade;
import org.D7noun.facades.VoucherFacade;
import org.D7noun.models.Voucher.VoucherType;
import org.D7noun.models.VoucherData;
import org.D7noun.models.VoucherData.DC;
import org.D7noun.models.accounts.Account;
import org.D7noun.models.accounts.Account.Currency;
import org.D7noun.service.AccountReportService;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.omnifaces.util.Ajax;
import org.omnifaces.util.Faces;

@ManagedBean
@ViewScoped
public class AccountReportController implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EJB
	private AccountReportService accountReportService;
	@EJB
	private AccountFacade accountFacade;
	@EJB
	private ItemFacade itemFacade;
	@EJB
	private VoucherFacade voucherFacade;
	private List<AccountReportDto> reportData = new ArrayList<AccountReportDto>();
	private List<VoucherData> voucherDatas = new ArrayList<VoucherData>();
	private List<Account> allAccounts = new ArrayList<Account>();

	private Account account;
	private Date fromDate;
	private Date toDate;
	private Currency currency;
	private double previousBalance = 0;
	private AccountReportDto previousAccountReport = new AccountReportDto();
	////////////////////////////////////
	////////////////////////////////////
	private double totalDr;
	private double totalCr;
	private CRDR totalCRDr;
	////////////////////////////////////
	////////////////////////////////////

	@PostConstruct
	public void init() {
		try {
			Calendar calendar = Calendar.getInstance();
			calendar.set(Calendar.DAY_OF_MONTH, 1);
			calendar.set(Calendar.MONTH, 0);
			fromDate = calendar.getTime();
			toDate = new Date();
			allAccounts = accountFacade.findAll();
			currency = Currency.DOLAR;
		} catch (Exception e) {
			e.printStackTrace();
			System.err.println("D7noun: AccountReportController.init");
		}
	}

	public void search() {
		try {

			totalDr = 0;
			totalCr = 0;
			previousBalance = 0;
			reportData = new ArrayList<>();
			previousAccountReport = new AccountReportDto();
			List<VoucherData> previouseVouchers = accountReportService.getVouchersByAccountBeforeDate(account,
					fromDate);
			for (VoucherData voucherData : previouseVouchers) {
				if (currency == Currency.DOLAR) {
					if (voucherData.getDc() == DC.D) {
						previousBalance += voucherData.getUsdEquivalent();
					} else {
						previousBalance -= voucherData.getUsdEquivalent();
					}
				} else {
					if (voucherData.getDc() == DC.D) {
						previousBalance += voucherData.getLlEquivalent();
					} else {
						previousBalance -= voucherData.getLlEquivalent();
					}
				}
			}
			previousAccountReport.setVoucherInfo(GeneralUtility.getResourceBundleString("previous_balance"));
			if (previousBalance > 0) {
				previousAccountReport.setCrdr(CRDR.DR);
				previousAccountReport.setDebit(previousBalance);
				previousAccountReport.setBalance(previousBalance);
				totalDr += previousAccountReport.getDebit();
			} else {
				previousAccountReport.setCrdr(CRDR.CR);
				previousAccountReport.setCredit(previousBalance * -1);
				previousAccountReport.setBalance(previousBalance * -1);
				totalCr += previousAccountReport.getCredit();
			}
			if (account != null) {
				voucherDatas = accountReportService.findVouchersByAccountsAndDates(account, fromDate, toDate);
				Iterator<VoucherData> iterator = voucherDatas.iterator();
				while (iterator.hasNext()) {
					VoucherData voucherData = iterator.next();
					AccountReportDto accountReportDto = new AccountReportDto();
					/////////////////////////////////
					/////////////////////////////////
					accountReportDto.setVoucherDate(voucherData.getVoucherDate());
					accountReportDto.setEntryDescription(voucherData.getEntryDescription());
					accountReportDto.setVoucherNumber(voucherData.getVoucherNumber());
					accountReportDto.setVoucherType(voucherData.getVoucherType());
					accountReportDto
							.setVoucherInfo(voucherData.getVoucherType().name() + " " + voucherData.getVoucherNumber());

					if (currency == Currency.DOLAR) {
						if (voucherData.getDc() == DC.D) {
							accountReportDto.setDebit(voucherData.getUsdEquivalent());
						} else {
							accountReportDto.setCredit(voucherData.getUsdEquivalent() * -1);
						}
					} else {
						if (voucherData.getDc() == DC.D) {
							accountReportDto.setDebit(voucherData.getLlEquivalent());
						} else {
							accountReportDto.setCredit(voucherData.getLlEquivalent() * -1);
						}
					}

					/////////////////////////////////
					/////////////////////////////////
					reportData.add(accountReportDto);
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
			System.err.println("D7noun: AccountReportController.search");
		}
		Collections.sort(reportData, new Comparator<AccountReportDto>() {
			@Override
			public int compare(AccountReportDto o1, AccountReportDto o2) {
				if (o1.getVoucherDate() == null) {
					return 1;
				}
				if (o2.getVoucherDate() == null) {
					return -1;
				}
				return o1.getVoucherDate().compareTo(o2.getVoucherDate());
			}
		});

		double balance = previousBalance;
		double balanceView = 0;
		for (AccountReportDto accountReportDto : reportData) {
			if (accountReportDto.getDebit() > 0) {
				balance = balance + accountReportDto.getDebit();
				if (balance < 0) {
					balanceView = balance * -1;
					accountReportDto.setCrdr(CRDR.CR);
				} else {
					balanceView = balance;
					accountReportDto.setCrdr(CRDR.DR);
				}
				accountReportDto.setBalance(balanceView);
				totalDr += accountReportDto.getDebit();
			} else {
				balance = balance - accountReportDto.getCredit();
				if (balance < 0) {
					balanceView = balance * -1;
					accountReportDto.setCrdr(CRDR.CR);
				} else {
					balanceView = balance;
					accountReportDto.setCrdr(CRDR.DR);
				}
				accountReportDto.setBalance(balanceView);
				totalCr += accountReportDto.getCredit();
			}
		}
		Ajax.oncomplete("PF('itemVar').filter()");
		Ajax.update("itemsDataTable");
	}

	public void exportToExcel() {

		try {

			// Create a Workbook
			Workbook workbook = new XSSFWorkbook(); // new HSSFWorkbook() for
													// generating `.xls` file

			/*
			 * CreationHelper helps us create instances of various things like DataFormat,
			 * Hyperlink, RichTextString etc, in a format (HSSF, XSSF) independent way
			 */
			CreationHelper createHelper = workbook.getCreationHelper();

			// Create a Sheet
			Sheet sheet = workbook.createSheet("Accounts");

			// Create a Font for styling header cells
			Font headerFont = workbook.createFont();
			headerFont.setFontHeightInPoints((short) 14);
			headerFont.setColor(IndexedColors.RED.getIndex());

			// Create a CellStyle with the font
			CellStyle headerCellStyle = workbook.createCellStyle();
			headerCellStyle.setFont(headerFont);
			headerCellStyle.setAlignment(HorizontalAlignment.RIGHT);

			// Create Cell Style for formatting Date
			CellStyle dateCellStyle = workbook.createCellStyle();
			dateCellStyle.setDataFormat(createHelper.createDataFormat().getFormat("dd-MM-yyyy"));
			dateCellStyle.setAlignment(HorizontalAlignment.RIGHT);

			Row descriptionRow = sheet.createRow(0);
			Cell descAccountName = descriptionRow.createCell(0);
			descAccountName.setCellValue(account.displayName());
			descAccountName.setCellStyle(headerCellStyle);

			Cell descFromDateText = descriptionRow.createCell(2);
			descFromDateText.setCellValue(GeneralUtility.getResourceBundleString("from_date"));
			Cell descFromDate = descriptionRow.createCell(3);
			descFromDate.setCellValue(fromDate);
			descFromDate.setCellStyle(dateCellStyle);
			Cell descToDateText = descriptionRow.createCell(4);
			descToDateText.setCellValue(GeneralUtility.getResourceBundleString("to_date"));
			Cell descToDate = descriptionRow.createCell(5);
			descToDate.setCellValue(toDate);
			descToDate.setCellStyle(dateCellStyle);

			// Create a Row
			Row headerRow = sheet.createRow(2);
			Cell headerVoucherInfo = headerRow.createCell(0);
			Cell headerDate = headerRow.createCell(1);
			Cell headerEntryDescription = headerRow.createCell(2);
			Cell headerDR = headerRow.createCell(3);
			Cell headerCR = headerRow.createCell(4);
			Cell headerBalance = headerRow.createCell(5);
			Cell headerType = headerRow.createCell(6);

			headerVoucherInfo.setCellValue(GeneralUtility.getResourceBundleString("voucher_info"));
			headerDate.setCellValue(GeneralUtility.getResourceBundleString("date"));
			headerEntryDescription.setCellValue(GeneralUtility.getResourceBundleString("entry_description"));
			headerDR.setCellValue("DR");
			headerCR.setCellValue("CR");
			headerBalance.setCellValue("Balance");
			headerType.setCellValue("CR/DR");


ticketing/src/main/webapp/view/reports/customer-general-report.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui"
	xmlns:of="http://omnifaces.org/functions">

<h:head></h:head>
<ui:decorate template="/template/masterTemplate.xhtml">
	<ui:param name="maintitle" value="#{app.customer_general_report}"></ui:param>
	<ui:param name="pageSubTitle" value="#{app.customer_general_report}"></ui:param>
	<ui:define name="breadcrumb-items">
		<li class="breadcrumb-item"><h:link outcome="home">#{app.home}</h:link></li>
		<li class="breadcrumb-item active"><strong>#{app.customer_general_report}</strong>
		</li>
	</ui:define>


	<ui:define name="contentInForm">

		<div class="ibox float-e-margins">
			<!-- / ibox-title -->
			<div class="ibox-content collapse show" id="main-info">
				<div class="widgets-container">

					<div class="row">
						<div class="col-md-3">
							<div class="form-group">
								<div class="col-md-4">
									<h:outputLabel value="#{app.from_date}"
										styleClass="control-label" />
								</div>
								<div class="col-md-8">
									<p:calendar id="fromDate" pattern="dd-MM-yyyy"
										value="#{customerGeneralReportController.fromDate}"
										showButtonPanel="true" navigator="true"
										inputStyleClass="form-control" />
								</div>
							</div>
						</div>
						<div class="col-md-3">
							<div class="form-group">
								<div class="col-md-4">
									<h:outputLabel value="#{app.to_date}"
										styleClass="control-label" />
								</div>
								<div class="col-md-8">
									<p:calendar id="toDate" pattern="dd-MM-yyyy"
										value="#{customerGeneralReportController.toDate}"
										showButtonPanel="true" navigator="true"
										inputStyleClass="form-control" />
								</div>
							</div>
						</div>
						<div class="col-md-1">
							<div class="margin-top-two">
								<h:commandLink
									action="#{customerGeneralReportController.search()}"
									styleClass="btn btn-success">
									<h:outputText value="#{app.search}" />
									<f:ajax execute="account fromDate toDate currency"
										render="itemsDataTable" />
								</h:commandLink>
							</div>
						</div>
						<div class="col-md-1">
							<div class="margin-top-two">
								<h:commandLink styleClass="btn btn-info exportToExcel"
									action="#{customerGeneralReportController.exportToExcel()}">
									<i class="fa fa-file-excel-o white" />
								</h:commandLink>
							</div>
						</div>
					</div>


					<div class="margin-top-two">
						<p:dataTable value="#{customerGeneralReportController.reportData}"
							var="item" id="itemsDataTable"
							emptyMessage="#{app.no_records_found}" rowIndexVar="rowIndex"
							paginator="true" paginatorPosition="bottom"
							paginatorAlwaysVisible="false"
							rowsPerPageTemplate="50,100,200,500,1000" rows="50"
							widgetVar="itemVar" draggableColumns="true">

							<p:column headerText="#" width="100">
								<h:outputLabel value="#{rowIndex + 1}" />
							</p:column>

							<p:column filterBy="#{item.customer.displayName()}"
								sortBy="#{item.customer.displayName()}"
								filterMatchMode="contains" width="200">
								<f:facet name="filter">
									<p:inputText onkeyup="PF('itemVar').filter()"
										placeholder="#{app.customer}" />
								</f:facet>
								<h:link styleClass="card-link" outcome="customer-card">
									<h:outputLabel value="#{item.customer.displayName()}"
										title="#{item.customer.displayName()}"
										styleClass="text-truncate" />
									<f:param name="id" value="#{item.customer.id}" />
								</h:link>
							</p:column>

							<p:column filterBy="#{item.price}" sortBy="#{item.price}"
								filterMatchMode="contains" width="100">
								<f:facet name="filter">
									<p:inputText onkeyup="PF('itemVar').filter()"
										placeholder="#{app.amount}" />
								</f:facet>
								<h:outputLabel value="#{item.price}" title="#{item.price}"
									styleClass="text-truncate" />
							</p:column>

							<p:column headerText="DC" filterBy="#{item.DC}"
								sortBy="#{item.DC}" filterMatchMode="contains" width="100">
								<f:facet name="filter">
									<p:inputText onkeyup="PF('itemVar').filter()" placeholder="DC" />
								</f:facet>
								<h:outputLabel value="#{item.DC}" title="#{item.DC}"
									styleClass="text-truncate" />
							</p:column>

						</p:dataTable>
					</div>
				</div>
			</div>
		</div>


	</ui:define>

</ui:decorate>
</html>

ticketing/src/main/webapp/view/reports/trial-balance.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui"
	xmlns:of="http://omnifaces.org/functions">

<h:head></h:head>
<ui:decorate template="/template/masterTemplate.xhtml">
	<ui:param name="maintitle" value="Trial Balance"></ui:param>
	<ui:param name="pageSubTitle" value="Trial Balance"></ui:param>
	<ui:define name="breadcrumb-items">
		<li class="breadcrumb-item"><h:link outcome="home">#{app.home}</h:link></li>
		<li class="breadcrumb-item active"><strong>Trial Balance</strong>
		</li>
	</ui:define>


	<ui:define name="contentInForm">

		<div class="ibox float-e-margins">
			<!-- / ibox-title -->
			<div class="ibox-content collapse show" id="main-info">
				<div class="widgets-container">


					<div class="row">
						<div class="col-md-3">
							<div class="form-group">
								<div class="col-md-12">
									<h:outputLabel value="#{app.from_date}"
										styleClass="control-label" />
								</div>
								<div class="col-md-12">
									<p:calendar id="fromDate" pattern="dd-MM-yyyy"
										value="#{tBController.fromDate}" showButtonPanel="true"
										navigator="true" inputStyleClass="form-control" />
								</div>
							</div>
						</div>
						<div class="col-md-3">
							<div class="form-group">
								<div class="col-md-12">
									<h:outputLabel value="#{app.to_date}"
										styleClass="control-label" />
								</div>
								<div class="col-md-12">
									<p:calendar id="toDate" pattern="dd-MM-yyyy"
										value="#{tBController.toDate}" showButtonPanel="true"
										navigator="true" inputStyleClass="form-control" />
								</div>
							</div>
						</div>
						<div class="col-md-3">
							<div class="form-group">
								<div class="col-md-12">
									<h:outputLabel value="#{app.from_account}"
										styleClass="control-label" />
								</div>
								<div class="col-md-12">
									<p:selectOneMenu id="fromType" value="#{tBController.fromType}"
										filterMatchMode="contains" filter="true">
										<f:selectItem />
										<f:selectItems value="#{tBController.allAccountTree}"
											var="item" itemValue="#{item.code}"
											itemLabel="#{item.displayName}" />
									</p:selectOneMenu>
								</div>
							</div>
						</div>
						<div class="col-md-3">
							<div class="form-group">
								<div class="col-md-12">
									<h:outputLabel value="#{app.to_account}"
										styleClass="control-label" />
								</div>
								<div class="col-md-12">
									<p:selectOneMenu id="toType" value="#{tBController.toType}"
										filterMatchMode="contains" filter="true">
										<f:selectItem />
										<f:selectItems value="#{tBController.allAccountTree}"
											var="item" itemValue="#{item.code}"
											itemLabel="#{item.displayName}" />
									</p:selectOneMenu>
								</div>
							</div>
						</div>
						<div class="col-md-3 ">
							<div class="margin-top-two">
								<p:selectOneButton id="currency"
									value="#{tBController.currency}">
									<f:selectItem itemLabel="DOLAR" itemValue="DOLAR" />
									<f:selectItem itemLabel="LIRA" itemValue="LIRA" />
								</p:selectOneButton>
							</div>
						</div>
						<div class="col-md-3 ">
							<div class="margin-top-two">
								<h:commandLink action="#{tBController.search()}"
									styleClass="btn btn-success">
									<f:ajax execute="fromDate toDate fromType toType currency"
										render="itemsDataTable" />
									<i class="fa fa-search" />
								</h:commandLink>
							</div>
						</div>
						<div class="col-md-3">
							<div class="margin-top-two">
								<h:commandLink styleClass="btn btn-info exportToExcel"
									action="#{tBController.exportToExcel()}">
									<i class="fa fa-file-excel-o white" />
								</h:commandLink>
							</div>
						</div>
						<div class="col-md-3">
							<div class="margin-top-two">
								<p:commandLink action="#{tBController.printOrder()}"
									styleClass="btn btn-danger" ajax="false">
									<i class="fa fa-file-pdf-o white" />
								</p:commandLink>
							</div>
						</div>
					</div>

					<div class="col-md-12 margin-top-one">

						<p:dataTable value="#{tBController.reportData}" var="item"
							id="itemsDataTable" emptyMessage="#{app.no_records_found}"
							rowIndexVar="rowIndex" paginator="true"
							paginatorPosition="bottom" paginatorAlwaysVisible="false"
							rowsPerPageTemplate="10,50,100,200,500,1000" rows="10"
							widgetVar="itemVar" draggableColumns="true">

							<p:column headerText="#" width="100">
								<h:outputLabel value="#{rowIndex + 1}" />
							</p:column>

							<p:column filterBy="#{item.code}" sortBy="#{item.code}"
								filterMatchMode="startsWith" width="120">
								<f:facet name="filter">
									<p:inputText onkeyup="PF('itemVar').filter()"
										placeholder="Code" />
								</f:facet>
								<h:outputLabel value="#{item.code}" title="#{item.code}"
									styleClass="text-truncate" />
							</p:column>

							<p:column filterBy="#{item.name}" sortBy="#{item.name}"
								filterMatchMode="contains">
								<f:facet name="filter">
									<p:inputText onkeyup="PF('itemVar').filter()"
										placeholder="Name" />
								</f:facet>
								<h:outputLabel value="#{item.name}" title="#{item.name}"
									styleClass="text-truncate" />
							</p:column>

							<p:column filterBy="#{item.debitStr}" sortBy="#{item.debitStr}"
								filterMatchMode="contains" width="150">
								<f:facet name="filter">
									<p:inputText onkeyup="PF('itemVar').filter()"
										placeholder="Debit" />
								</f:facet>
								<h:outputLabel value="#{item.debitStr}" title="#{item.debitStr}"
									styleClass="text-truncate number-format" />
							</p:column>

							<p:column filterBy="#{item.creditStr}" sortBy="#{item.creditStr}"
								filterMatchMode="contains" width="150">
								<f:facet name="filter">
									<p:inputText onkeyup="PF('itemVar').filter()"
										placeholder="Credit" />
								</f:facet>
								<h:outputLabel value="#{item.creditStr}"
									title="#{item.creditStr}"
									styleClass="text-truncate number-format" />
							</p:column>

							<p:column filterBy="#{item.balanceStr}"
								sortBy="#{item.balanceStr}" filterMatchMode="contains"
								width="150">
								<f:facet name="filter">
									<p:inputText onkeyup="PF('itemVar').filter()"
										placeholder="Balance" />
								</f:facet>
								<h:outputLabel value="#{item.balanceStr}"
									title="#{item.balanceStr}"
									styleClass="text-truncate number-format" />
							</p:column>

							<p:column filterBy="#{item.crDr}" sortBy="#{item.crDr}"
								filterMatchMode="contains" width="120">
								<f:facet name="filter">
									<p:inputText onkeyup="PF('itemVar').filter()"
										placeholder="CRDR" />
								</f:facet>
								<h:outputLabel value="#{item.crDr}" title="#{item.crDr}"
									styleClass="text-truncate" />
							</p:column>

							<p:columnGroup type="footer">
								<p:row>
									<p:column />
									<p:column />
									<p:column />
									<p:column>
										<f:facet name="footer">
											<h:outputLabel value="#{tBController.debitTotalStr}"
												title="#{tBController.debitTotalStr}"
												styleClass="text-truncate number-format" />
										</f:facet>
									</p:column>
									<p:column>
										<f:facet name="footer">
											<h:outputLabel value="#{tBController.creditTotalStr}"
												title="#{tBController.creditTotalStr}"
												styleClass="text-truncate number-format" />
										</f:facet>
									</p:column>
									<p:column>
										<f:facet name="footer">
											<h:outputLabel value="#{tBController.balanceStr}"
												title="#{tBController.balanceStr}"
												styleClass="text-truncate number-format" />
										</f:facet>
									</p:column>
									<p:column>
										<f:facet name="footer">
											<h:outputLabel value="#{tBController.crDr}"
												title="#{tBController.crDr}"
												styleClass="text-truncate number-format" />
										</f:facet>
									</p:column>
								</p:row>
							</p:columnGroup>

						</p:dataTable>
					</div>
				</div>
			</div>
		</div>
	</ui:define>

</ui:decorate>
</html>