ticketing/src/main/java/org/D7noun/models/Voucher.java
package org.D7noun.models;

import java.io.Serializable;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.D7noun.abstraction.AbstractEntity;
import org.D7noun.abstraction.GeneralUtility;
import org.D7noun.dto.CustomerGeneralReportDto;
import org.D7noun.models.VoucherData.DC;
import org.D7noun.models.items.Item;

@Entity
@NamedQueries({
		@NamedQuery(name = Voucher.getMaxVoucherNumberByType, query = "SELECT max(v.voucherNumber) FROM Voucher v WHERE v.voucherType = :voucherType"),
		@NamedQuery(name = Voucher.getVouchersByAccountAndDates, query = "SELECT vd FROM VoucherData vd WHERE vd.account = :account AND vd.voucherDate >= :fromDate AND vd.voucherDate <= :toDate ORDER BY vd.creationDate asc"),
		@NamedQuery(name = Voucher.getVouchersByAccountBeforeDate, query = "SELECT vd FROM VoucherData vd WHERE vd.account = :account AND vd.voucherDate < :date"),
		@NamedQuery(name = CustomerGeneralReportDto.getVoucherDatasBetweenDates, query = "SELECT vd FROM VoucherData vd WHERE vd.voucherDate >= :fromDate AND vd.voucherDate <= :toDate AND vd.account.dtype = 'Customer'"),
		@NamedQuery(name = Voucher.getAllVoucherDatasBetweenTwoDates, query = "SELECT vd FROM VoucherData vd WHERE vd.voucherDate >= :fromDate AND vd.voucherDate <= :toDate"),
		@NamedQuery(name = Voucher.getAllBetweenTwoDates, query = "SELECT v FROM Voucher v WHERE v.voucherDate >= :fromDate AND v.voucherDate <= :toDate ORDER BY v.voucherDate"),
		@NamedQuery(name = Voucher.getAllBetweenTwoDatesByType, query = "SELECT v FROM Voucher v WHERE v.voucherDate >= :fromDate AND v.voucherDate <= :toDate AND v.voucherType = :voucherType ORDER BY v.voucherDate"),
		@NamedQuery(name = Voucher.getVoucherIdFromNumberAndType, query = "SELECT v.id FROM Voucher v WHERE v.voucherNumber = :voucherNumber AND v.voucherType = :voucherType"),
		@NamedQuery(name = Voucher.findVoucherByItem, query = "SELECT i.voucher FROM Item i WHERE i = :item ") })
public class Voucher extends AbstractEntity implements Serializable {

	public static final String getMaxVoucherNumberByType = "Voucher.getMaxVoucherNumberByType";
	public static final String getVouchersByAccountAndDates = "Voucher.getVouchersByAccountAndDates";
	public static final String getVouchersByAccountBeforeDate = "Voucher.getVouchersByAccountBeforeDate";
	public static final String getAllVoucherDatasBetweenTwoDates = "Voucher.getAllVoucherDatasBetweenTwoDates";
	public static final String getAllBetweenTwoDates = "Voucher.getAllBetweenTwoDates";
	public static final String getAllBetweenTwoDatesByType = "Voucher.getAllBetweenTwoDatesByType";
	public static final String getVoucherIdFromNumberAndType = "Voucher.getVoucherIdFromNumberAndType";
	public static final String findVoucherByItem = "Voucher.findVoucherByItem";

	public enum VoucherType {
		JV("JV"), PV("PV"), RV("RV"), RE("RE"), TI("TI"), WB("WB"), VS("VS"), FS("FS"), HS("HS"), TS("TS");

		private String value;

		private VoucherType(String value) {
			this.value = value;
		}

		public String getValue() {
			return value;
		}
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Enumerated(EnumType.STRING)
	private VoucherType voucherType;

	private long voucherNumber;

	@OrderBy
	@Temporal(TemporalType.DATE)
	private Date voucherDate;

	@OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
	@JoinColumn(name = "voucher_id")
	private List<Item> items = new ArrayList<Item>();

	@OneToMany(mappedBy = "voucher", cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
	private List<VoucherData> voucherDatas = new ArrayList<VoucherData>();

	/**
	 * 
	 * Voucher Data
	 * 
	 */

	public String voucherCode() {
		if (voucherNumber != 0 && voucherType != null) {
			return voucherType + " " + voucherNumber;
		}
		return GeneralUtility.getResourceBundleString("check_voucher_saved");
	}

	public double totalDrAC() {
		double sum = 0;
		for (VoucherData voucherData : voucherDatas) {
			if (voucherData.getDc() == DC.D) {
				sum += voucherData.getAcAmount();
			}
		}
		return sum;
	}

	public double totalCrAC() {
		double sum = 0;
		for (VoucherData voucherData : voucherDatas) {
			if (voucherData.getDc() == DC.C) {
				sum += voucherData.getAcAmount();
			}
		}
		return sum;
	}

	public double balanceAC() {
		return totalDrAC() - totalCrAC();
	}

	/////////////////////////

	public double totalDrLL() {
		double sum = 0;
		for (VoucherData voucherData : voucherDatas) {
			if (voucherData.getDc() == DC.D) {
				sum += voucherData.getLlEquivalent();
			}
		}
		DecimalFormat decimalFormat = new DecimalFormat("##.00");
		return Double.parseDouble(decimalFormat.format(sum));
	}

	public double totalCrLL() {
		double sum = 0;
		for (VoucherData voucherData : voucherDatas) {
			if (voucherData.getDc() == DC.C) {
				sum += voucherData.getLlEquivalent();
			}
		}
		DecimalFormat decimalFormat = new DecimalFormat("##.00");
		return Double.parseDouble(decimalFormat.format(sum));
	}

	public double balanceLL() {
		return totalDrLL() - totalCrLL();
	}

	/////////////////////////

	public double totalDrUSD() {
		double sum = 0;
		for (VoucherData voucherData : voucherDatas) {
			if (voucherData.getDc() == DC.D) {
				sum += voucherData.getUsdEquivalent();
			}
		}
		DecimalFormat decimalFormat = new DecimalFormat("##.00");
		return Double.parseDouble(decimalFormat.format(sum));
	}

	public double totalCrUSD() {
		double sum = 0;
		for (VoucherData voucherData : voucherDatas) {
			if (voucherData.getDc() == DC.C) {
				sum += voucherData.getUsdEquivalent();
			}
		}
		DecimalFormat decimalFormat = new DecimalFormat("##.00");
		return Double.parseDouble(decimalFormat.format(sum));
	}

	public double balanceUSD() {
		return totalDrUSD() - totalCrUSD();
	}
	///////////////////

	public Voucher addNewVoucherData(VoucherData voucherData) {
		if (voucherData != null) {
			voucherData.setVoucher(this);
			voucherData.setVoucherDate(this.voucherDate);
			voucherData.setVoucherNumber(this.voucherNumber);
			voucherData.setVoucherType(this.voucherType);
			this.getVoucherDatas().add(voucherData);
		}
		return this;
	}

	public Voucher deleteVoucherData(List<VoucherData> voucherDatas) {
		if (voucherDatas != null) {
			this.getVoucherDatas().removeAll(voucherDatas);
		}
		return this;
	}

	public Voucher addNewItem(Item item) {
		if (item != null) {
			item.setVoucherDate(this.getVoucherDate());
			item.setVoucherNumber(this.voucherNumber);
			item.setVoucherType(this.voucherType);
			item.setVoucher(this);
			this.getItems().add(item);
		}
		return this;
	}

	public Voucher removeItem(Item item) {
		if (item != null) {
			item.setVoucher(null);
		}
		return this;
	}

	/**
	 * 
	 * D7noun: GETTERS&SETTERS
	 * 
	 */

	/**
	 * @return the voucherType
	 */
	public VoucherType getVoucherType() {
		return voucherType;
	}

	/**
	 * @param voucherType the voucherType to set
	 */
	public void setVoucherType(VoucherType voucherType) {
		this.voucherType = voucherType;
	}

	/**
	 * @return the voucherDate
	 */
	public Date getVoucherDate() {
		return voucherDate;
	}

	/**
	 * @param voucherDate the voucherDate to set
	 */
	public void setVoucherDate(Date voucherDate) {
		this.voucherDate = voucherDate;
	}

	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * @return the voucherDatas
	 */
	public List<VoucherData> getVoucherDatas() {
		return voucherDatas;
	}

	/**
	 * @param voucherDatas the voucherDatas to set
	 */
	public void setVoucherDatas(List<VoucherData> voucherDatas) {
		this.voucherDatas = voucherDatas;
	}

	/**
	 * @return the voucherNumber
	 */
	public long getVoucherNumber() {
		return voucherNumber;
	}

	/**
	 * @param voucherNumber the voucherNumber to set
	 */
	public void setVoucherNumber(long voucherNumber) {
		this.voucherNumber = voucherNumber;
	}

	public List<Item> getItems() {
		return items;
	}

	public void setItems(List<Item> items) {
		this.items = items;
	}

	public String getTicketNumberByVoucher() {
		for (VoucherData voucherData : voucherDatas) {
			if (voucherData.getEntryDescription() == null
					&& voucherData.getEntryDescription().contains("Ticket Number: ")) {
				return voucherData.getEntryDescription().split("Ticket Number: ")[1];
			}
		}
		return "";
	}

	@PrePersist
	@PreUpdate
	public void preupdate() {
		this.getVoucherDatas().forEach(vd -> {
			vd.setVoucherDate(voucherDate);
			vd.setVoucherNumber(voucherNumber);
			vd.setVoucherType(voucherType);
		});
	}
}

ticketing/src/main/java/org/D7noun/controllers/VoucherListController.java
package org.D7noun.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.D7noun.facades.VoucherFacade;
import org.D7noun.models.Voucher;
import org.D7noun.models.Voucher.VoucherType;
import org.omnifaces.util.Ajax;
import org.omnifaces.util.Faces;

@ManagedBean
@ViewScoped
public class VoucherListController implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EJB
	private VoucherFacade voucherFacade;
	private List<Voucher> allVouchers = new ArrayList<Voucher>();
	private List<Voucher> selectedVouchers = new ArrayList<Voucher>();

	///////////////////////////////////////
	private Date fromDate;
	private Date toDate;
	private VoucherType voucherType;

	///////////////////////////
	///////////////////////////
	///////////////////////////

	public void init() {
		try {
			if (!Faces.isPostback()) {
				fromDate = new Date();
				toDate = new Date();
				allVouchers = voucherFacade.getAllBetweenTwoDates(fromDate, toDate);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void search() {
		try {
			if (voucherType != null) {
				allVouchers = voucherFacade.getAllBetweenTwoDatesByType(fromDate, toDate, voucherType);
			} else {
				allVouchers = voucherFacade.getAllBetweenTwoDates(fromDate, toDate);
			}
			Ajax.oncomplete("PF('itemVar').filter()");
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void delete(Voucher voucher) {
		voucherFacade.remove(voucher);
		allVouchers = voucherFacade.getAllBetweenTwoDates(fromDate, toDate);
	}

	public void deleteList() {
		voucherFacade.remove(selectedVouchers);
		allVouchers = voucherFacade.getAllBetweenTwoDates(fromDate, toDate);
	}

	/**
	 * 
	 * 
	 * 
	 * 
	 * D7noun: GETTERS&SETTERS
	 * 
	 * 
	 * 
	 * 
	 */

	/**
	 * @return the voucherFacade
	 */
	public VoucherFacade getVoucherFacade() {
		return voucherFacade;
	}

	/**
	 * @param voucherFacade the voucherFacade to set
	 */
	public void setVoucherFacade(VoucherFacade voucherFacade) {
		this.voucherFacade = voucherFacade;
	}

	/**
	 * @return the allVouchers
	 */
	public List<Voucher> getAllVouchers() {
		return allVouchers;
	}

	/**
	 * @param allVouchers the allVouchers to set
	 */
	public void setAllVouchers(List<Voucher> allVouchers) {
		this.allVouchers = allVouchers;
	}

	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * @return the fromDate
	 */
	public Date getFromDate() {
		return fromDate;
	}

	/**
	 * @param fromDate the fromDate to set
	 */
	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	/**
	 * @return the toDate
	 */
	public Date getToDate() {
		return toDate;
	}

	/**
	 * @param toDate the toDate to set
	 */
	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public List<Voucher> getSelectedVouchers() {
		return selectedVouchers;
	}

	public void setSelectedVouchers(List<Voucher> selectedVouchers) {
		this.selectedVouchers = selectedVouchers;
	}

	public VoucherType getVoucherType() {
		return voucherType;
	}

	public void setVoucherType(VoucherType voucherType) {
		this.voucherType = voucherType;
	}

}

ticketing/src/main/webapp/view/voucher/voucher-list.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui"
	xmlns:of="http://omnifaces.org/functions">

<h:head></h:head>
<ui:decorate template="/template/masterTemplate.xhtml">


	<f:metadata>
		<f:event type="preRenderView"
			listener="#{voucherListController.init()}" />
	</f:metadata>


	<ui:param name="maintitle" value="#{app.voucher_list}"></ui:param>
	<ui:param name="pageSubTitle" value="#{app.voucher_list}"></ui:param>
	<ui:define name="breadcrumb-items">
		<li class="breadcrumb-item"><h:link outcome="home">#{app.home}</h:link></li>
		<li class="breadcrumb-item active"><strong>#{app.voucher_list}</strong>
		</li>
	</ui:define>


	<ui:define name="contentInForm">


		<div class="row">
			<div class="col-md-3">
				<div class="form-group">
					<div class="col-md-4">
						<h:outputLabel value="#{app.from_date}" styleClass="control-label" />
					</div>
					<div class="col-md-8">
						<p:calendar id="fromDate" pattern="dd-MM-yyyy"
							value="#{voucherListController.fromDate}" showButtonPanel="true"
							navigator="true" inputStyleClass="form-control" />
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="form-group">
					<div class="col-md-4">
						<h:outputLabel value="#{app.to_date}" styleClass="control-label" />
					</div>
					<div class="col-md-8">
						<p:calendar id="toDate" pattern="dd-MM-yyyy"
							value="#{voucherListController.toDate}" showButtonPanel="true"
							navigator="true" inputStyleClass="form-control" />
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="form-group">
					<div class="col-md-4">
						<h:outputLabel value="#{app.type}" styleClass="control-label" />
					</div>
					<div class="col-md-8">
						<p:selectOneMenu id="voucherType"
							value="#{voucherListController.voucherType}"
							placeholder="#{app.type}">
							<f:selectItem />
							<f:selectItem itemValue="JV" itemLabel="JV" />
							<f:selectItem itemValue="PV" itemLabel="PV" />
							<f:selectItem itemValue="RV" itemLabel="RV" />
							<f:selectItem itemValue="RE" itemLabel="RE" />
							<f:selectItem itemValue="TI" itemLabel="TI" />
							<f:selectItem itemValue="VS" itemLabel="VS" />
							<f:selectItem itemValue="FS" itemLabel="FS" />
							<f:selectItem itemValue="HS" itemLabel="HS" />
							<f:selectItem itemValue="TS" itemLabel="TS" />
						</p:selectOneMenu>
					</div>
				</div>
			</div>

			<div class="col-md-3">
				<h:commandLink action="#{voucherListController.search()}"
					styleClass="btn btn-success margin-top-two">
					<h:outputText value="#{app.search}" />
					<f:ajax execute="fromDate toDate voucherType"
						render="itemsDataTable" />
				</h:commandLink>
			</div>
		</div>

		<p:dataTable value="#{voucherListController.allVouchers}"
			selection="#{voucherListController.selectedVouchers}" var="item"
			id="itemsDataTable" emptyMessage="#{app.no_records_found}"
			rowIndexVar="rowIndex" paginator="true" paginatorPosition="bottom"
			paginatorAlwaysVisible="false" rowKey="#{item.id}"
			rowsPerPageTemplate="50,100,200,500,1000" rows="50"
			widgetVar="itemVar" draggableColumns="true">

			<p:column selectionMode="multiple"
				style="width:32px;text-align:center" />

			<p:column headerText="#" width="100">#{rowIndex + 1}</p:column>

			<p:column width="30" style="text-align: center">
				<p:commandLink styleClass="" title="#{app.delete}" process="@this"
					update="growl" oncomplete="PF('itemVar').filter()"
					actionListener="#{voucherListController.delete(item)}">
					<i class="fa fa-trash alert-danger no-background"></i>
					<p:confirm header="#{app.confirmation}"
						message="#{app.msg_are_you_sure_to_delete}" icon="ui-icon-alert" />
				</p:commandLink>
			</p:column>

			<p:column filterBy="#{item.voucherDate}" sortBy="#{item.voucherDate}"
				filterMatchMode="contains" width="200">
				<f:facet name="filter">
					<p:inputText onkeyup="PF('itemVar').filter()"
						placeholder="#{app.voucher_date}" />
				</f:facet>
				<h:outputLabel value="#{item.voucherDate}"
					title="#{item.voucherDate}" styleClass="text-truncate">
					<f:convertDateTime pattern="dd-MM-yyyy" />
				</h:outputLabel>
			</p:column>

			<p:column filterBy="#{item.voucherCode()}"
				sortBy="#{item.voucherCode()}" filterMatchMode="contains"
				width="200">
				<f:facet name="filter">
					<p:inputText onkeyup="PF('itemVar').filter()"
						placeholder="#{app.voucher_number}" />
				</f:facet>
				<h:link outcome="voucher-card" styleClass="card-link">
					<h:outputLabel value="#{item.voucherCode()}"
						title="#{item.voucherCode()}" styleClass="text-truncate" />
					<f:param name="id" value="#{item.id}" />
				</h:link>
			</p:column>

			<p:column filterBy="#{item.ticketNumberByVoucher}"
				sortBy="#{item.ticketNumberByVoucher}" filterMatchMode="contains"
				width="200">
				<f:facet name="filter">
					<p:inputText onkeyup="PF('itemVar').filter()"
						placeholder="Ticket Number" />
				</f:facet>
				<h:outputLabel value="#{item.ticketNumberByVoucher}"
					title="#{item.ticketNumberByVoucher}" styleClass="text-truncate" />
			</p:column>

			<p:column filterBy="#{item.voucherType}" sortBy="#{item.voucherType}"
				filterMatchMode="contains" width="150">
				<f:facet name="filter">
					<p:selectOneMenu placeholder="#{app.type}"
						onchange="PF('itemVar').filter()">
						<f:selectItem />
						<f:selectItem itemValue="JV" itemLabel="JV" />
						<f:selectItem itemValue="PV" itemLabel="PV" />
						<f:selectItem itemValue="RV" itemLabel="RV" />
						<f:selectItem itemValue="RE" itemLabel="RE" />
						<f:selectItem itemValue="TI" itemLabel="TI" />
						<f:selectItem itemValue="VS" itemLabel="VS" />
						<f:selectItem itemValue="FS" itemLabel="FS" />
						<f:selectItem itemValue="HS" itemLabel="HS" />
						<f:selectItem itemValue="TS" itemLabel="TS" />
					</p:selectOneMenu>
				</f:facet>
				<h:outputLabel value="#{item.voucherType}"
					title="#{item.voucherType}" styleClass="text-truncate" />
			</p:column>

			<p:column filterBy="#{item.totalCrLL()}" sortBy="#{item.totalCrLL()}"
				filterMatchMode="contains" width="200">
				<f:facet name="filter">
					<p:inputText onkeyup="PF('itemVar').filter()"
						placeholder="#{app.total_cr_ll}" />
				</f:facet>
				<h:outputLabel value="#{item.totalCrLL()}"
					title="#{item.totalCrLL()}"
					styleClass="text-truncate direction_ltr">
					<f:convertNumber locale="en-US" />
				</h:outputLabel>
			</p:column>

			<p:column filterBy="#{item.totalDrLL()}" sortBy="#{item.totalDrLL()}"
				filterMatchMode="contains" width="200">
				<f:facet name="filter">
					<p:inputText onkeyup="PF('itemVar').filter()"
						placeholder="#{app.total_dr_ll}" />
				</f:facet>
				<h:outputLabel value="#{item.totalDrLL()}"
					title="#{item.totalDrLL()}"
					styleClass="text-truncate direction_ltr">
					<f:convertNumber locale="en-US" />
				</h:outputLabel>
			</p:column>

			<p:column filterBy="#{item.totalCrUSD()}"
				sortBy="#{item.totalCrUSD()}" filterMatchMode="contains" width="200">
				<f:facet name="filter">
					<p:inputText onkeyup="PF('itemVar').filter()"
						placeholder="#{app.total_cr_usd}" />
				</f:facet>
				<h:outputLabel value="#{item.totalCrUSD()}"
					title="#{item.totalCrUSD()}"
					styleClass="text-truncate direction_ltr">
					<f:convertNumber locale="en-US" />
				</h:outputLabel>
			</p:column>

			<p:column filterBy="#{item.totalDrUSD()}"
				sortBy="#{item.totalDrUSD()}" filterMatchMode="contains" width="200">
				<f:facet name="filter">
					<p:inputText onkeyup="PF('itemVar').filter()"
						placeholder="#{app.total_dr_usd}" />
				</f:facet>
				<h:outputLabel value="#{item.totalDrUSD()}"
					title="#{item.totalDrUSD()}"
					styleClass="text-truncate direction_ltr">
					<f:convertNumber locale="en-US" />
				</h:outputLabel>
			</p:column>



		</p:dataTable>


		<p:confirmDialog global="true">
			<p:commandButton value="#{app.yes}" type="button"
				styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
			<p:commandButton value="#{app.no}" type="button"
				styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
		</p:confirmDialog>

	</ui:define>

	<ui:define name="contentFooter">
		<div class="pull-left">
			<p:commandLink styleClass="btn btn-danger margin-left-one"
				title="#{app.delete}" process="@form" update="growl"
				oncomplete="PF('itemVar').filter()"
				actionListener="#{voucherListController.deleteList()}">
				<h:outputText styleClass="white" value="#{app.delete_many}" />
				<p:confirm header="#{app.confirmation}"
					message="#{app.msg_are_you_sure_to_delete}" icon="ui-icon-alert" />
			</p:commandLink>
			<h:link outcome="voucher-card" target="_blank"
				styleClass="btn btn-success">
				<h:outputLabel value="#{app.new_card}" styleClass="white" />
			</h:link>
		</div>
	</ui:define>


</ui:decorate>
</html>